### ISSUE TITLE
How to describe a algorithm with AADL 

### ISSUE THREAD

**Issue by phamhoanganhbk** [juli1/aadl-book#1]
Hi @juli1 ,

I am a newbie of AADL and i am reading your book and your example of car control.
But I still don't really understand how we can describe control algorithms (like PID, backstepping....)

Could you please give me some explains ?

Many thanks,  
Hoang Anh

**Comment by juli1** [comment]
Hi,

The book is not focused on describing algorithms - it focuses on architectural concerns. For describing algorithms or behavior, you will have to use the behavior annex of the language.

**Comment by phamhoanganhbk** [comment]
Hi @juli1,
Thank for your reply, 
I saw some documents which said that Aadl doesn’t describe algorithms. I am very confused. As your reply, could you please give me any documents ? 
Thank for your help,

**Comment by juli1** [comment]
A search on google scholar for "aadl behavior annex" will give you a reasonable number of papers talking about this.

Closing this issue now.
